theme: jekyll-theme-hacker
title: Elías D. Nino-Ruiz, Ph.D. 
description: Bookmark this to keep an eye on my updates!
github:
  repository_url: https://github.com/enino84/
  is_user_page: true
  is_project_page: false
